# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a0fa7dd9afcdd74a025bcdd58bc15a238e20d20622b6be4cb1c79150c34d63e27bc13c43381b1d4d552f8c1cd651caf7baef303e47a332d53c380a7f2cec013

test:
  secret_key_base: 8d15bf9e8534c8d4c50bb1870da0acc131faf1865878b3c9c7d50f72d6e982b7a5b70935e34141d37464e182483bd72f164292149fb56c1db478f8286defdf54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
